[pid: 374513|app: 0|req: 7/78] 219.239.227.245 () {44 vars in 871 bytes} [Mon Aug 28 01:42:35 2023] POST /api/user/register/ => generated 152485 bytes in 270 msecs (HTTP/1.1 500) 9 headers in 343 bytes (1 switches on core 0)
Internal Server Error: /api/user/register/
Traceback (most recent call last):
  File "/home/summer/miniconda3/envs/django/lib/python3.9/site-packages/django/db/backends/mysql/base.py", line 75, in execute
    return self.cursor.execute(query, args)
  File "/home/summer/miniconda3/envs/django/lib/python3.9/site-packages/MySQLdb/cursors.py", line 206, in execute
    res = self._query(query)
  File "/home/summer/miniconda3/envs/django/lib/python3.9/site-packages/MySQLdb/cursors.py", line 319, in _query
    db.query(q)
  File "/home/summer/miniconda3/envs/django/lib/python3.9/site-packages/MySQLdb/connections.py", line 254, in query
    _mysql.connection.query(self, query)
MySQLdb.OperationalError: (1048, "Column 'current_team_id' cannot be null")

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/summer/miniconda3/envs/django/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/summer/miniconda3/envs/django/lib/python3.9/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/summer/summer_backend/./user/authentication.py", line 47, in valid_per
    return func(request, *args, **kwargs)
  File "/home/summer/summer_backend/./user/views.py", line 64, in register
    user = User.objects.create(username=username, password=pswd1, email=email)
  File "/home/summer/miniconda3/envs/django/lib/python3.9/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/summer/miniconda3/envs/django/lib/python3.9/site-packages/django/db/models/query.py", line 658, in create
    obj.save(force_insert=True, using=self.db)
  File "/home/summer/miniconda3/envs/django/lib/python3.9/site-packages/django/db/models/base.py", line 814, in save
    self.save_base(
  File "/home/summer/miniconda3/envs/django/lib/python3.9/site-packages/django/db/models/base.py", line 877, in save_base
    updated = self._save_table(
  File "/home/summer/miniconda3/envs/django/lib/python3.9/site-packages/django/db/models/base.py", line 1020, in _save_table
    results = self._do_insert(
  File "/home/summer/miniconda3/envs/django/lib/python3.9/site-packages/django/db/models/base.py", line 1061, in _do_insert
    return manager._insert(
  File "/home/summer/miniconda3/envs/django/lib/python3.9/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/summer/miniconda3/envs/django/lib/python3.9/site-packages/django/db/models/query.py", line 1805, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
  File "/home/summer/miniconda3/envs/django/lib/python3.9/site-packages/django/db/models/sql/compiler.py", line 1822, in execute_sql
    cursor.execute(sql, params)
  File "/home/summer/miniconda3/envs/django/lib/python3.9/site-packages/django/db/backends/utils.py", line 102, in execute
    return super().execute(sql, params)
  File "/home/summer/miniconda3/envs/django/lib/python3.9/site-packages/django/db/backends/utils.py", line 67, in execute
    return self._execute_with_wrappers(
  File "/home/summer/miniconda3/envs/django/lib/python3.9/site-packages/django/db/backends/utils.py", line 80, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/home/summer/miniconda3/envs/django/lib/python3.9/site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "/home/summer/miniconda3/envs/django/lib/python3.9/site-packages/django/db/backends/mysql/base.py", line 80, in execute
    raise IntegrityError(*tuple(e.args))
django.db.utils.IntegrityError: (1048, "Column 'current_team_id' cannot be null")
[pid: 374517|app: 0|req: 30/79] 219.239.227.245 () {44 vars in 871 bytes} [Mon Aug 28 01:42:35 2023] POST /api/user/register/ => generated 152500 bytes in 555 msecs (HTTP/1.1 500) 9 headers in 343 bytes (1 switches on core 1)
Internal Server Error: /api/user/register/
Traceback (most recent call last):
  File "/home/summer/miniconda3/envs/django/lib/python3.9/site-packages/django/db/backends/mysql/base.py", line 75, in execute
    return self.cursor.execute(query, args)
  File "/home/summer/miniconda3/envs/django/lib/python3.9/site-packages/MySQLdb/cursors.py", line 206, in execute
    res = self._query(query)
  File "/home/summer/miniconda3/envs/django/lib/python3.9/site-packages/MySQLdb/cursors.py", line 319, in _query
    db.query(q)
  File "/home/summer/miniconda3/envs/django/lib/python3.9/site-packages/MySQLdb/connections.py", line 254, in query
    _mysql.connection.query(self, query)
MySQLdb.OperationalError: (1048, "Column 'current_team_id' cannot be null")

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/summer/miniconda3/envs/django/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/summer/miniconda3/envs/django/lib/python3.9/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/summer/summer_backend/./user/authentication.py", line 47, in valid_per
    return func(request, *args, **kwargs)
  File "/home/summer/summer_backend/./user/views.py", line 64, in register
    user = User.objects.create(username=username, password=pswd1, email=email)
  File "/home/summer/miniconda3/envs/django/lib/python3.9/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/summer/miniconda3/envs/django/lib/python3.9/site-packages/django/db/models/query.py", line 658, in create
    obj.save(force_insert=True, using=self.db)
  File "/home/summer/miniconda3/envs/django/lib/python3.9/site-packages/django/db/models/base.py", line 814, in save
    self.save_base(
  File "/home/summer/miniconda3/envs/django/lib/python3.9/site-packages/django/db/models/base.py", line 877, in save_base
    updated = self._save_table(
  File "/home/summer/miniconda3/envs/django/lib/python3.9/site-packages/django/db/models/base.py", line 1020, in _save_table
    results = self._do_insert(
  File "/home/summer/miniconda3/envs/django/lib/python3.9/site-packages/django/db/models/base.py", line 1061, in _do_insert
    return manager._insert(
  File "/home/summer/miniconda3/envs/django/lib/python3.9/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/summer/miniconda3/envs/django/lib/python3.9/site-packages/django/db/models/query.py", line 1805, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
  File "/home/summer/miniconda3/envs/django/lib/python3.9/site-packages/django/db/models/sql/compiler.py", line 1822, in execute_sql
    cursor.execute(sql, params)
  File "/home/summer/miniconda3/envs/django/lib/python3.9/site-packages/django/db/backends/utils.py", line 102, in execute
    return super().execute(sql, params)
  File "/home/summer/miniconda3/envs/django/lib/python3.9/site-packages/django/db/backends/utils.py", line 67, in execute
    return self._execute_with_wrappers(
  File "/home/summer/miniconda3/envs/django/lib/python3.9/site-packages/django/db/backends/utils.py", line 80, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/home/summer/miniconda3/envs/django/lib/python3.9/site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "/home/summer/miniconda3/envs/django/lib/python3.9/site-packages/django/db/backends/mysql/base.py", line 80, in execute
    raise IntegrityError(*tuple(e.args))
django.db.utils.IntegrityError: (1048, "Column 'current_team_id' cannot be null")
[pid: 374516|app: 0|req: 30/80] 219.239.227.245 () {44 vars in 871 bytes} [Mon Aug 28 01:42:35 2023] POST /api/user/register/ => generated 152500 bytes in 264 msecs (HTTP/1.1 500) 9 headers in 343 bytes (1 switches on core 1)
Internal Server Error: /api/user/register/
Traceback (most recent call last):
  File "/home/summer/miniconda3/envs/django/lib/python3.9/site-packages/django/db/backends/mysql/base.py", line 75, in execute
    return self.cursor.execute(query, args)
  File "/home/summer/miniconda3/envs/django/lib/python3.9/site-packages/MySQLdb/cursors.py", line 206, in execute
    res = self._query(query)
  File "/home/summer/miniconda3/envs/django/lib/python3.9/site-packages/MySQLdb/cursors.py", line 319, in _query
    db.query(q)
  File "/home/summer/miniconda3/envs/django/lib/python3.9/site-packages/MySQLdb/connections.py", line 254, in query
    _mysql.connection.query(self, query)
MySQLdb.OperationalError: (1048, "Column 'current_team_id' cannot be null")

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/summer/miniconda3/envs/django/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/summer/miniconda3/envs/django/lib/python3.9/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/summer/summer_backend/./user/authentication.py", line 47, in valid_per
    return func(request, *args, **kwargs)
  File "/home/summer/summer_backend/./user/views.py", line 64, in register
    user = User.objects.create(username=username, password=pswd1, email=email)
  File "/home/summer/miniconda3/envs/django/lib/python3.9/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/summer/miniconda3/envs/django/lib/python3.9/site-packages/django/db/models/query.py", line 658, in create
    obj.save(force_insert=True, using=self.db)
  File "/home/summer/miniconda3/envs/django/lib/python3.9/site-packages/django/db/models/base.py", line 814, in save
    self.save_base(
  File "/home/summer/miniconda3/envs/django/lib/python3.9/site-packages/django/db/models/base.py", line 877, in save_base
    updated = self._save_table(
  File "/home/summer/miniconda3/envs/django/lib/python3.9/site-packages/django/db/models/base.py", line 1020, in _save_table
    results = self._do_insert(
  File "/home/summer/miniconda3/envs/django/lib/python3.9/site-packages/django/db/models/base.py", line 1061, in _do_insert
    return manager._insert(
  File "/home/summer/miniconda3/envs/django/lib/python3.9/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/summer/miniconda3/envs/django/lib/python3.9/site-packages/django/db/models/query.py", line 1805, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
  File "/home/summer/miniconda3/envs/django/lib/python3.9/site-packages/django/db/models/sql/compiler.py", line 1822, in execute_sql
    cursor.execute(sql, params)
  File "/home/summer/miniconda3/envs/django/lib/python3.9/site-packages/django/db/backends/utils.py", line 102, in execute
    return super().execute(sql, params)
  File "/home/summer/miniconda3/envs/django/lib/python3.9/site-packages/django/db/backends/utils.py", line 67, in execute
    return self._execute_with_wrappers(
  File "/home/summer/miniconda3/envs/django/lib/python3.9/site-packages/django/db/backends/utils.py", line 80, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/home/summer/miniconda3/envs/django/lib/python3.9/site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "/home/summer/miniconda3/envs/django/lib/python3.9/site-packages/django/db/backends/mysql/base.py", line 80, in execute
    raise IntegrityError(*tuple(e.args))
django.db.utils.IntegrityError: (1048, "Column 'current_team_id' cannot be null")
[pid: 374517|app: 0|req: 31/81] 219.239.227.245 () {44 vars in 871 bytes} [Mon Aug 28 01:45:55 2023] POST /api/user/register/ => generated 152451 bytes in 57 msecs (HTTP/1.1 500) 9 headers in 343 bytes (1 switches on core 0)
Internal Server Error: /api/user/register/
Traceback (most recent call last):
  File "/home/summer/miniconda3/envs/django/lib/python3.9/site-packages/django/db/backends/mysql/base.py", line 75, in execute
    return self.cursor.execute(query, args)
  File "/home/summer/miniconda3/envs/django/lib/python3.9/site-packages/MySQLdb/cursors.py", line 206, in execute
    res = self._query(query)
  File "/home/summer/miniconda3/envs/django/lib/python3.9/site-packages/MySQLdb/cursors.py", line 319, in _query
    db.query(q)
  File "/home/summer/miniconda3/envs/django/lib/python3.9/site-packages/MySQLdb/connections.py", line 254, in query
    _mysql.connection.query(self, query)
MySQLdb.OperationalError: (1048, "Column 'current_team_id' cannot be null")

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/summer/miniconda3/envs/django/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/summer/miniconda3/envs/django/lib/python3.9/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/summer/summer_backend/./user/authentication.py", line 47, in valid_per
    return func(request, *args, **kwargs)
  File "/home/summer/summer_backend/./user/views.py", line 64, in register
    user = User.objects.create(username=username, password=pswd1, email=email)
  File "/home/summer/miniconda3/envs/django/lib/python3.9/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/summer/miniconda3/envs/django/lib/python3.9/site-packages/django/db/models/query.py", line 658, in create
    obj.save(force_insert=True, using=self.db)
  File "/home/summer/miniconda3/envs/django/lib/python3.9/site-packages/django/db/models/base.py", line 814, in save
    self.save_base(
  File "/home/summer/miniconda3/envs/django/lib/python3.9/site-packages/django/db/models/base.py", line 877, in save_base
    updated = self._save_table(
  File "/home/summer/miniconda3/envs/django/lib/python3.9/site-packages/django/db/models/base.py", line 1020, in _save_table
    results = self._do_insert(
  File "/home/summer/miniconda3/envs/django/lib/python3.9/site-packages/django/db/models/base.py", line 1061, in _do_insert
    return manager._insert(
  File "/home/summer/miniconda3/envs/django/lib/python3.9/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/summer/miniconda3/envs/django/lib/python3.9/site-packages/django/db/models/query.py", line 1805, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
  File "/home/summer/miniconda3/envs/django/lib/python3.9/site-packages/django/db/models/sql/compiler.py", line 1822, in execute_sql
    cursor.execute(sql, params)
  File "/home/summer/miniconda3/envs/django/lib/python3.9/site-packages/django/db/backends/utils.py", line 102, in execute
    return super().execute(sql, params)
  File "/home/summer/miniconda3/envs/django/lib/python3.9/site-packages/django/db/backends/utils.py", line 67, in execute
    return self._execute_with_wrappers(
  File "/home/summer/miniconda3/envs/django/lib/python3.9/site-packages/django/db/backends/utils.py", line 80, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/home/summer/miniconda3/envs/django/lib/python3.9/site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "/home/summer/miniconda3/envs/django/lib/python3.9/site-packages/django/db/backends/mysql/base.py", line 80, in execute
    raise IntegrityError(*tuple(e.args))
django.db.utils.IntegrityError: (1048, "Column 'current_team_id' cannot be null")
[pid: 374517|app: 0|req: 32/82] 219.239.227.245 () {44 vars in 871 bytes} [Mon Aug 28 01:45:59 2023] POST /api/user/register/ => generated 152466 bytes in 56 msecs (HTTP/1.1 500) 9 headers in 343 bytes (1 switches on core 1)
SIGINT/SIGTERM received...killing workers...
worker 1 buried after 1 seconds
worker 2 buried after 1 seconds
worker 3 buried after 1 seconds
worker 4 buried after 1 seconds
goodbye to uWSGI.
*** Starting uWSGI 2.0.21 (64bit) on [Mon Aug 28 01:51:14 2023] ***
compiled with version: 11.2.0 on 28 March 2023 07:25:39
os: Linux-5.4.0-139-generic #156-Ubuntu SMP Fri Jan 20 17:27:18 UTC 2023
nodename: VM-8-13-ubuntu
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 2
current working directory: /home/summer/summer_backend
writing pidfile to uwsgi.pid
detected binary path: /home/summer/miniconda3/envs/django/bin/uwsgi
chdir() to /home/summer/summer_backend
your processes number limit is 7547
your memory page size is 4096 bytes
detected max file descriptor number: 1048576
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to TCP address 127.0.0.1:8000 fd 6
Python version: 3.9.16 (main, Mar  8 2023, 14:00:05)  [GCC 11.2.0]
Set PythonHome to /home/summer/miniconda3/envs/django
Python main interpreter initialized at 0xfdfef0
python threads support enabled
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 416880 bytes (407 KB) for 8 cores
*** Operational MODE: preforking+threaded ***
added /home/summer/miniconda3/envs/django/lib/python3.9/ to pythonpath.
WSGI app 0 (mountpoint='') ready in 2 seconds on interpreter 0xfdfef0 pid: 390400 (default app)
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 390400)
spawned uWSGI worker 1 (pid: 390421, cores: 2)
spawned uWSGI worker 2 (pid: 390423, cores: 2)
spawned uWSGI worker 3 (pid: 390425, cores: 2)
spawned uWSGI worker 4 (pid: 390427, cores: 2)
